[package]
name = "nbf"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[features]
types = []
state = ["types"]
core = ["state", "types"]
plugins = ["core", "types"]

[dependencies]
